artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/865612534885903594/75da886f022948a2be3b28c373fa8b98/artifacts
end_time: null
entry_point_name: ''
experiment_id: '865612534885903594'
lifecycle_stage: active
run_id: 75da886f022948a2be3b28c373fa8b98
run_name: dazzling-moth-599
source_name: ''
source_type: 4
source_version: ''
start_time: 1773315196753
status: 1
tags: []
user_id: root
