artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/1cad9ab4ed49449cba58a7d09c16def3/artifacts
end_time: 1773270538287
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: 1cad9ab4ed49449cba58a7d09c16def3
run_name: treasured-robin-79
source_name: ''
source_type: 4
source_version: ''
start_time: 1773269799163
status: 3
tags: []
user_id: root
