artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/05ac41deeb2d437fb6ac0decbd505279/artifacts
end_time: 1773258658530
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: 05ac41deeb2d437fb6ac0decbd505279
run_name: mercurial-hawk-799
source_name: ''
source_type: 4
source_version: ''
start_time: 1773258167609
status: 3
tags: []
user_id: root
