artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/bb37ea5a78ca474db7ada5868bf6ba61/artifacts
end_time: 1773287343245
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: bb37ea5a78ca474db7ada5868bf6ba61
run_name: resilient-shoat-827
source_name: ''
source_type: 4
source_version: ''
start_time: 1773286621152
status: 3
tags: []
user_id: root
