artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/affd806b68fe4665b3fe2cd619f3fae0/artifacts
end_time: 1773251676660
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: affd806b68fe4665b3fe2cd619f3fae0
run_name: thundering-crow-745
source_name: ''
source_type: 4
source_version: ''
start_time: 1773251178328
status: 3
tags: []
user_id: root
