artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/331eabd86fb34f79bfde7c2bcb12a3f1/artifacts
end_time: 1773257719005
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: 331eabd86fb34f79bfde7c2bcb12a3f1
run_name: judicious-ray-388
source_name: ''
source_type: 4
source_version: ''
start_time: 1773257225568
status: 3
tags: []
user_id: root
