artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/07db15af97ef459e9ceef5a1d2874baa/artifacts
end_time: 1773265133332
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: 07db15af97ef459e9ceef5a1d2874baa
run_name: intelligent-wolf-375
source_name: ''
source_type: 4
source_version: ''
start_time: 1773264398861
status: 3
tags: []
user_id: root
