artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/865612534885903594/1b694a7388b24b9b9a0e0c1c44e0b0aa/artifacts
end_time: null
entry_point_name: ''
experiment_id: '865612534885903594'
lifecycle_stage: active
run_id: 1b694a7388b24b9b9a0e0c1c44e0b0aa
run_name: sassy-conch-133
source_name: ''
source_type: 4
source_version: ''
start_time: 1773316069434
status: 1
tags: []
user_id: root
