artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/865612534885903594/eb34eb8a7dcd47bfab2f82c7ae1a9bee/artifacts
end_time: null
entry_point_name: ''
experiment_id: '865612534885903594'
lifecycle_stage: active
run_id: eb34eb8a7dcd47bfab2f82c7ae1a9bee
run_name: marvelous-moose-955
source_name: ''
source_type: 4
source_version: ''
start_time: 1773316068927
status: 1
tags: []
user_id: root
