artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/ab4a5ad8ee0b4da794771d4f88c9d3c3/artifacts
end_time: null
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: ab4a5ad8ee0b4da794771d4f88c9d3c3
run_name: merciful-squid-708
source_name: ''
source_type: 4
source_version: ''
start_time: 1773244801274
status: 1
tags: []
user_id: root
