artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/7434d0ba012b457dae4dfb7eeb4fb1cc/artifacts
end_time: 1773268319757
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: 7434d0ba012b457dae4dfb7eeb4fb1cc
run_name: secretive-loon-314
source_name: ''
source_type: 4
source_version: ''
start_time: 1773267574921
status: 3
tags: []
user_id: root
