artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/55f253128e9f4ade9569bd27856feab4/artifacts
end_time: null
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: 55f253128e9f4ade9569bd27856feab4
run_name: big-fly-879
source_name: ''
source_type: 4
source_version: ''
start_time: 1773245213046
status: 1
tags: []
user_id: root
