artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/12d32fd7db8a4e15ba09dfac576db81f/artifacts
end_time: 1773261591042
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: 12d32fd7db8a4e15ba09dfac576db81f
run_name: intelligent-fly-858
source_name: ''
source_type: 4
source_version: ''
start_time: 1773261106160
status: 3
tags: []
user_id: root
