artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/edc491fdfb144d3e83cebdf632ae733e/artifacts
end_time: 1773271540009
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: edc491fdfb144d3e83cebdf632ae733e
run_name: peaceful-doe-997
source_name: ''
source_type: 4
source_version: ''
start_time: 1773270782668
status: 3
tags: []
user_id: root
