artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/a0addc6fc0d74b61bf1c963c04a0a72e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: a0addc6fc0d74b61bf1c963c04a0a72e
run_name: grandiose-skunk-579
source_name: ''
source_type: 4
source_version: ''
start_time: 1773261439123
status: 1
tags: []
user_id: root
