artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/dea3eac407a1479b9bdd3cd594ae8e41/artifacts
end_time: 1773263513681
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: dea3eac407a1479b9bdd3cd594ae8e41
run_name: agreeable-stag-588
source_name: ''
source_type: 4
source_version: ''
start_time: 1773263035634
status: 3
tags: []
user_id: root
