artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/faec83aacb3d40ac9e080a59d1aa5ee7/artifacts
end_time: 1773260560372
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: faec83aacb3d40ac9e080a59d1aa5ee7
run_name: tasteful-snail-470
source_name: ''
source_type: 4
source_version: ''
start_time: 1773260078663
status: 3
tags: []
user_id: root
