artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/be11abd9d09a44908a5829958921e58b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: be11abd9d09a44908a5829958921e58b
run_name: shivering-bass-36
source_name: ''
source_type: 4
source_version: ''
start_time: 1773249369066
status: 1
tags: []
user_id: root
