artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/acc3f144fd9546958fbb8b1a8d92527c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: acc3f144fd9546958fbb8b1a8d92527c
run_name: flawless-shrike-923
source_name: ''
source_type: 4
source_version: ''
start_time: 1773249183359
status: 1
tags: []
user_id: root
