artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/bd37476f7aad4e18bd86c2ff4eb1dc8b/artifacts
end_time: 1773285790745
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: bd37476f7aad4e18bd86c2ff4eb1dc8b
run_name: rebellious-hog-228
source_name: ''
source_type: 4
source_version: ''
start_time: 1773285081458
status: 3
tags: []
user_id: root
