artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/184baf43afbd44aba8afa23f76a4bd01/artifacts
end_time: null
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: 184baf43afbd44aba8afa23f76a4bd01
run_name: mysterious-swan-807
source_name: ''
source_type: 4
source_version: ''
start_time: 1773249841228
status: 1
tags: []
user_id: root
