artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/74ac0c7bceec4ac4a7a0b7ef61d60a94/artifacts
end_time: null
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: 74ac0c7bceec4ac4a7a0b7ef61d60a94
run_name: mercurial-shrew-27
source_name: ''
source_type: 4
source_version: ''
start_time: 1773245212823
status: 1
tags: []
user_id: root
