artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/805141331734350883/ad1d196cf5bf420fb59cace6b726bed9/artifacts
end_time: 1773310936570
entry_point_name: ''
experiment_id: '805141331734350883'
lifecycle_stage: active
run_id: ad1d196cf5bf420fb59cace6b726bed9
run_name: rebellious-robin-419
source_name: ''
source_type: 4
source_version: ''
start_time: 1773309625473
status: 3
tags: []
user_id: root
