artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/c5295fb954bb4c60b4c5677ff91604a0/artifacts
end_time: null
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: c5295fb954bb4c60b4c5677ff91604a0
run_name: mercurial-flea-417
source_name: ''
source_type: 4
source_version: ''
start_time: 1773249392724
status: 1
tags: []
user_id: root
