artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/140703615045363024/959db4f21a894e0ab6ec2ee9fadffec7/artifacts
end_time: 1773283825678
entry_point_name: ''
experiment_id: '140703615045363024'
lifecycle_stage: active
run_id: 959db4f21a894e0ab6ec2ee9fadffec7
run_name: overjoyed-worm-554
source_name: ''
source_type: 4
source_version: ''
start_time: 1773283099563
status: 3
tags: []
user_id: root
