artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/c1eefe3d73e7487d933ead6be5b429aa/artifacts
end_time: 1773258671141
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: c1eefe3d73e7487d933ead6be5b429aa
run_name: secretive-stork-442
source_name: ''
source_type: 4
source_version: ''
start_time: 1773258179211
status: 3
tags: []
user_id: root
