artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/140703615045363024/a5f8cbc6c24c4fcab6de56450a58f454/artifacts
end_time: null
entry_point_name: ''
experiment_id: '140703615045363024'
lifecycle_stage: active
run_id: a5f8cbc6c24c4fcab6de56450a58f454
run_name: respected-fowl-886
source_name: ''
source_type: 4
source_version: ''
start_time: 1773268615047
status: 1
tags: []
user_id: root
