artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/47c38d04aa604411a54e051ba3bacfd0/artifacts
end_time: null
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: 47c38d04aa604411a54e051ba3bacfd0
run_name: loud-eel-506
source_name: ''
source_type: 4
source_version: ''
start_time: 1773249391888
status: 1
tags: []
user_id: root
