artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/589e0a34cfe34873bd9fefd8f20b3bea/artifacts
end_time: 1773253044903
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: 589e0a34cfe34873bd9fefd8f20b3bea
run_name: selective-snail-642
source_name: ''
source_type: 4
source_version: ''
start_time: 1773252544425
status: 3
tags: []
user_id: root
