artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/e1fba5e781a34bf4a0722dcbaf61df9f/artifacts
end_time: 1773253522628
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: e1fba5e781a34bf4a0722dcbaf61df9f
run_name: kindly-quail-491
source_name: ''
source_type: 4
source_version: ''
start_time: 1773253025981
status: 3
tags: []
user_id: root
