artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/63ec89929a3f4a99a99abeae2db4eed6/artifacts
end_time: 1773287207226
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: 63ec89929a3f4a99a99abeae2db4eed6
run_name: righteous-shark-880
source_name: ''
source_type: 4
source_version: ''
start_time: 1773286498910
status: 3
tags: []
user_id: root
