artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/6d5615fac1b74d74afab50a0d77ae0fc/artifacts
end_time: null
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: 6d5615fac1b74d74afab50a0d77ae0fc
run_name: sincere-roo-93
source_name: ''
source_type: 4
source_version: ''
start_time: 1773250342651
status: 1
tags: []
user_id: root
