artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/9e1786af342d4586acab7b7daaf4ac7c/artifacts
end_time: 1773265134314
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: 9e1786af342d4586acab7b7daaf4ac7c
run_name: grandiose-zebra-160
source_name: ''
source_type: 4
source_version: ''
start_time: 1773264662593
status: 3
tags: []
user_id: root
