artifact_uri: file:///content/drive/MyDrive/mlflow_runs3.0/915299191210141273/dc6ee7be93014d37af580df4afcee2bf/artifacts
end_time: 1773279135414
entry_point_name: ''
experiment_id: '915299191210141273'
lifecycle_stage: active
run_id: dc6ee7be93014d37af580df4afcee2bf
run_name: indecisive-horse-778
source_name: ''
source_type: 4
source_version: ''
start_time: 1773278378206
status: 3
tags: []
user_id: root
