artifact_location: file:///content/drive/MyDrive/mlflow_runs/652724939092415161
creation_time: 1773310084178
experiment_id: '652724939092415161'
last_update_time: 1773310084178
lifecycle_stage: active
name: FashionMNIST_Unlearningrate2.0
workspace: default
