artifact_uri: file:///content/drive/MyDrive/mlflow_runs2.0/915032625154962509/efed2311867c4ddc8e72c8cb4bd988da/artifacts
end_time: 1773256541020
entry_point_name: ''
experiment_id: '915032625154962509'
lifecycle_stage: active
run_id: efed2311867c4ddc8e72c8cb4bd988da
run_name: treasured-wasp-96
source_name: ''
source_type: 4
source_version: ''
start_time: 1773256046113
status: 3
tags: []
user_id: root
