artifact_uri: file:///content/drive/MyDrive/mlflow_runs/382214112253506520/9eaeefb0a8194bbebea7e37b82123ce6/artifacts
end_time: 1773257629353
entry_point_name: ''
experiment_id: '382214112253506520'
lifecycle_stage: active
run_id: 9eaeefb0a8194bbebea7e37b82123ce6
run_name: righteous-boar-296
source_name: ''
source_type: 4
source_version: ''
start_time: 1773257141285
status: 3
tags: []
user_id: root
